(function(g){var window=this;'use strict';var V1=function(k){k.publish("cardstatechange",k.ow()&&k.n5()?1:0)},HF=function(k,U){var n=g.Qs(U);
const Z=n?U:arguments;for(n=n?0:1;n<Z.length;n++){if(k==null)return;k=k[Z[n]]}return k},nrV=function(k){const U=g.fK(k);
k=g.xr(k);return new g.J5(U.x,U.y,k.width,k.height)},ZK7=function(k,U,n){let Z;
return Z=g.ka(k,U,function(){g.io(Z);n.apply(k,arguments)},{})},bp=function(k){k=g.$k(k);
delete R7[k];g.Gp(R7)&&hP&&hP.stop()},r52=function(){hP||(hP=new g.iX(function(){CAp()},20));
const k=hP;k.isActive()||k.start()},CAp=function(){var k=g.tS();
g.tm(R7,function(U){L5i(U,k)});
g.Gp(R7)||r52()},z1=function(k,U,n,Z){g.gp.call(this);
if(!Array.isArray(k)||!Array.isArray(U))throw Error("Start and end parameters must be arrays");if(k.length!=U.length)throw Error("Start and end points must be the same length");this.B=k;this.L=U;this.duration=n;this.W=Z;this.coords=[];this.progress=this.V=0;this.J=null},L5i=function(k,U){U<k.startTime&&(k.endTime=U+k.endTime-k.startTime,k.startTime=U);
k.progress=(U-k.startTime)/(k.endTime-k.startTime);k.progress>1&&(k.progress=1);k.V=1E3/(U-k.J);k.J=U;F5m(k,k.progress);k.progress==1?(k.S=0,bp(k),k.onFinish(),k.wb()):k.isPlaying()&&k.e$()},F5m=function(k,U){typeof k.W==="function"&&(U=k.W(U));
k.coords=Array(k.B.length);for(let n=0;n<k.B.length;n++)k.coords[n]=(k.L[n]-k.B[n])*U+k.B[n]},vri=function(k,U){g.g5.call(this,k);
this.coords=U.coords;this.x=U.coords[0];this.y=U.coords[1];this.z=U.coords[2];this.duration=U.duration;this.progress=U.progress;this.fps=U.V;this.state=U.S},Q1=function(k,U,n,Z,C){z1.call(this,U,n,Z,C);
this.element=k},KA=function(k,U,n,Z,C){if(U.length!=2||n.length!=2)throw Error("Start and end points must be 2D");
Q1.call(this,k,U,n,Z,C)},OK8=function(k){return Math.pow(k,3)},wls=function(k){return 3*k*k-2*k*k*k},T1=function(k){return k.baseUrl||null},a7=function(k,U){return g.GN(g.fz(k,U),n=>!!n)},uVb=function(k,U,n){function Z(Kz){var WJ=Kz.hovercardButton;
if(!WJ)return null;WJ=WJ.subscribeButtonRenderer;if(!WJ)return null;const M6=r(WJ.unsubscribedButtonText),Na=r(WJ.subscribedButtonText);let jU,a0;WJ.subscribed?(jU=r(WJ.subscriberCountWithUnsubscribeText),a0=r(WJ.subscriberCountText)):(jU=r(WJ.subscriberCountText),a0=r(WJ.subscriberCountWithSubscribeText));let G8=null;return Kz.signinEndpoint&&((G8=HF(Kz,"signinEndpoint","webNavigationEndpointData","url"))||(G8=g.e(WJ.signInEndpoint?.commandMetadata,g.bZ)?.url),!G8)?null:M6&&(Na||G8)?{subscribed:WJ.subscribed,
subscribeText:M6,subscribeCount:jU,unsubscribeText:Na,unsubscribeCount:a0,enabled:WJ.enabled,signinUrl:G8,classic:Kz.useClassicSubscribeButton}:null}
function C(Kz){if(Kz){var WJ=[],M6=Kz.videoId;M6&&WJ.push("v="+M6);(M6=Kz.playlistId)&&WJ.push("list="+M6);(Kz=Kz.startTimeSeconds)&&WJ.push("t="+Kz);return"/watch?"+WJ.join("&")}}
function r(Kz){if(!Kz)return null;const WJ=Kz.simpleText;return WJ?WJ:Kz.runs?g.fz(Kz.runs,M6=>M6.text).join(""):null}
U=U.endscreenElementRenderer;if(!U)return null;const L=U.style,F=U.endpoint||{};let v=null;var O=null,w=!1;let u=null,X=null,E=null,V=null;var Q=!1;let p=null,I=null;var t=null;let J=null,P=null,ra=null;if(L==="VIDEO")g.e(F,g.BC)?v=g.e(F,g.BC).url:(ra=g.e(F,g.A$),v=C(ra)),O=!1,u=k,U.thumbnailOverlays?(w=U.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,X=r(w.text),w=w.style==="LIVE"):X=r(U.videoDuration);else if(L==="PLAYLIST")g.e(F,g.BC)?v=g.e(F,g.BC).url:(ra=g.e(F,g.A$),v=C(ra)),O=!1,u=
k,E=r(U.playlistLength);else if(L==="CHANNEL"){if(Q=HF(F,"browseEndpoint","browseId"))V=Q,v=`/channel/${V}`;O=!1;u="new";(Q=!!U.isSubscribe)?p=Z(U):I=r(U.subscribersText)}else L==="WEBSITE"?((t=HF(F,"urlEndpoint","url"))&&(v=t),O=!0,u="new",t=U.icon.thumbnails[0].url):L==="CREATOR_MERCHANDISE"&&(U.productPrice&&(J=r(U.productPrice)),U.additionalFeesText&&(P=r(U.additionalFeesText)),(O=HF(F,"urlEndpoint","url"))&&(v=O),O=!0,u="new");k=HF(U,"title","accessibility","accessibilityData","label");const Lz=
U.endpoint?U.endpoint.clickTrackingParams:null;let oP="";if(U.metadata){const Kz=r(U.metadata);Kz&&(oP=Kz)}return{id:`element-${n}`,type:L,title:r(U.title),metadata:oP,callToAction:r(U.callToAction),A5:U.image,iconUrl:t,left:Number(U.left),width:Number(U.width),top:Number(U.top),aspectRatio:Number(U.aspectRatio),startMs:Math.floor(Number(U.startMs)),endMs:Math.floor(Number(U.endMs)),videoDuration:X,jO:w,playlistLength:E,channelId:V,subscribeButton:p,subscribersText:I,isSubscribe:Q,targetUrl:v||null,
Q2:O,sessionData:Lz?{itct:Lz}:null,jq:u,E5:k?k:null,isPlaceholder:U.isPlaceholder,impressionUrls:a7(U.impressionUrls||[],T1),nX:a7(U.hovercardShowUrls||[],T1),clickUrls:a7(F.loggingUrls||[],T1),visualElement:g.bf(U.trackingParams),productPrice:J,additionalFeesText:P,watchEndpoint:ra||null}},$t=function(k,U){const n={startMs:Math.floor(Number(k.startMs)),
impressionUrls:a7(k.impressionUrls||[],T1),elements:a7(k.elements||[],(Z,C)=>uVb(U,Z,C))};
k.trackingParams&&(n.visualElement=g.bf(k.trackingParams));return n},pA=function(k){return k.player.U().playerStyle==="creator-endscreen-editor"},grV=function(k){return k.player.getVideoData().wm?"current":k.D?"new":"current"},Nn=function(k,U,n=!0){k.player.Wn("creatorendscreen");
k.j&&(k.j.dispose(),k.j=null,k.W.dispose(),k.W=null);for(var Z of Object.values(k.B))Z.dispose();k.B={};k.V={};k.X.length>0&&(k.X.forEach(C=>{C.dispose()}),k.X.length=0);
k.S&&(g.Oe(k.S,"ytp-ce-element-show"),k.S.setAttribute("aria-hidden","true"));k.L=0;if((k.endscreen=U)&&U.elements){n&&XlE(k);n=[];Z=new g.sc(U.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});n.push(Z);k.player.U().B||(k.j=new g.l({Z:"div",A:"ytp-ce-shadow"}),g.$Z(k.player,k.j.element,4),k.W=new g.Wf(k.j,200));for(Z=0;Z<U.elements.length;++Z){const C=U.elements[Z],r=Erm(k,C);if(!r){g.ed(new g.h_("buildEndscreenElement null",C));continue}k.B[C.id]=r;k.V[C.id]=C;g.$Z(k.player,
r.element,4);const L=new g.sc(C.startMs,C.endMs,{id:"ytp-ce-element-"+C.id,namespace:"creatorendscreen"});n.push(L);A52(k,r,C)}k.player.oA(n);k.DP()}},ds_=function(k){var U=k.player.getVideoData(),n=U.videoId;
k.J&&k.J.abort();n={method:"POST",onFinish:C=>{var r=k.J=null;C.status===200&&(C=C.responseText,C.substring(0,3)===")]}"&&(C=C.substring(3),r=JSON.parse(C),r=$t(r,grV(k))));Nn(k,r)},
urlParams:{v:n},withCredentials:!0};k.D&&(n.urlParams.ptype="embedded");const Z=U.Jg;Z&&(n.postParams={ad_tracking:Z});if(U=g.g6U(U))if(U=g.De(U),U=g.BV(U))k.J=g.xX(U,n)},XlE=function(k){const U=g.Kf(),n=g.Tz();
n&&U&&k.endscreen.visualElement&&g.kU(g.cR)(void 0,n,U,k.endscreen.visualElement)},Erm=function(k,U){var n=null;
switch(U.type){case "VIDEO":k={Z:"div",O4:["ytp-ce-element","ytp-ce-video"],N:{tabindex:"0","aria-label":U.E5||"","aria-hidden":"true"},G:[{Z:"div",A:"ytp-ce-element-shadow"},{Z:"div",A:"ytp-ce-covering-image",N:tP(U)},{Z:"div",A:"ytp-ce-covering-shadow-top"},{Z:"a",A:"ytp-ce-covering-overlay",N:{href:I7(k,U.targetUrl),tabindex:"-1"},G:[{Z:"div",O4:["ytp-ce-video-title","ytp-webkit-ellipsis"],N:{dir:g.hi(U.title||"")},zJ:U.title},{Z:"div",A:U.jO?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
zJ:U.videoDuration||void 0}]}]};n=new g.l(k);break;case "PLAYLIST":k={Z:"div",O4:["ytp-ce-element","ytp-ce-playlist"],N:{tabindex:"0","aria-label":U.E5||"","aria-hidden":"true"},G:[{Z:"div",A:"ytp-ce-element-shadow"},{Z:"div",A:"ytp-ce-covering-image",N:tP(U)},{Z:"div",A:"ytp-ce-covering-shadow-top"},{Z:"a",A:"ytp-ce-covering-overlay",N:{href:I7(k,U.targetUrl),tabindex:"-1"},G:[{Z:"div",O4:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],N:{dir:g.hi(U.title||"")},zJ:U.title},{Z:"div",A:"ytp-ce-playlist-count",
G:[{Z:"div",A:"ytp-ce-playlist-icon"},{Z:"div",A:"ytp-ce-playlist-count-text",zJ:U.playlistLength||void 0}]}]}]};n=new g.l(k);break;case "CHANNEL":n={Z:"div",O4:["ytp-ce-element","ytp-ce-channel",U.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],N:{tabindex:"0","aria-label":U.E5||"","aria-hidden":"true"},G:[{Z:"div",A:"ytp-ce-element-shadow"},{Z:"div",A:"ytp-ce-expanding-overlay",G:[{Z:"div",A:"ytp-ce-expanding-overlay-hider"},{Z:"div",A:"ytp-ce-expanding-overlay-background"},{Z:"div",A:"ytp-ce-expanding-overlay-content",
G:[{Z:"div",A:"ytp-ce-expanding-overlay-body",G:[{Z:"div",A:"ytp-ce-expanding-overlay-body-padding",G:[{Z:"a",O4:["ytp-ce-channel-title","ytp-ce-link"],N:{href:I7(k,U.targetUrl),target:"_blank",tabindex:"-1",dir:g.hi(U.title||"")},zJ:U.title},U.subscribeButton?{Z:"div",A:"ytp-ce-subscribe-container",G:[{Z:"div",A:"ytp-ce-channel-subscribe"}]}:"",U.subscribersText?{Z:"div",A:"ytp-ce-channel-subscribers-text",zJ:U.subscribersText}:"",U.metadata?{Z:"div",O4:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],zJ:U.metadata}:""]}]}]}]},{Z:"div",A:"ytp-ce-expanding-image",N:tP(U)}]};n=new g.l(n);const C=g.mf(document,"div","ytp-ce-channel-subscribe",n.element)[0];if(U.subscribeButton&&U.channelId){g.F_(C,"ytp-ce-subscribe-button");let r;if(k.player.U().B){var Z=null;r=U.sessionData.itct}else Z="endscreen",r=null;Z=new g.X7(U.subscribeButton.subscribeText,U.subscribeButton.subscribeCount,U.subscribeButton.unsubscribeText,U.subscribeButton.unsubscribeCount,!!U.subscribeButton.enabled,!!U.subscribeButton.classic,
U.channelId,!!U.subscribeButton.subscribed,Z,r,k.player,!1);C.appendChild(Z.element);k.X.push(Z)}break;case "WEBSITE":k={Z:"div",O4:["ytp-ce-element","ytp-ce-website"],N:{tabindex:"0","aria-label":U.E5||"","aria-hidden":"true"},G:[{Z:"div",A:"ytp-ce-element-shadow"},{Z:"div",A:"ytp-ce-expanding-overlay",G:[{Z:"div",A:"ytp-ce-expanding-overlay-hider"},{Z:"div",A:"ytp-ce-expanding-overlay-background"},{Z:"div",A:"ytp-ce-expanding-overlay-content",G:[{Z:"div",A:"ytp-ce-expanding-overlay-body",G:[{Z:"div",
A:"ytp-ce-expanding-overlay-body-padding",G:[{Z:"div",A:"ytp-ce-website-title",N:{dir:g.hi(U.title||"")},zJ:U.title},{Z:"div",A:"ytp-ce-website-metadata",zJ:U.metadata},{Z:"a",O4:["ytp-ce-website-goto","ytp-ce-link"],N:{href:I7(k,U.targetUrl),target:"_blank",tabindex:"-1"},zJ:U.callToAction}]}]}]}]},{Z:"div",A:"ytp-ce-expanding-image",N:tP(U)},{Z:"div",A:"ytp-ce-expanding-icon",N:V6b(U.iconUrl)}]};n=new g.l(k);break;case "CREATOR_MERCHANDISE":n="",U.productPrice&&(n={Z:"div",A:"ytp-ce-merchandise-price-container",
G:[{Z:"div",A:"ytp-ce-merchandise-price",zJ:U.productPrice}]},U.additionalFeesText&&n.G.push({Z:"div",A:"ytp-ce-merchandise-additional-fees",zJ:U.additionalFeesText})),k={Z:"div",O4:["ytp-ce-element","ytp-ce-merchandise"],N:{tabindex:"0","aria-label":U.E5||"","aria-hidden":"true"},G:[{Z:"div",A:"ytp-ce-element-shadow"},{Z:"div",A:"ytp-ce-expanding-overlay",G:[{Z:"div",A:"ytp-ce-expanding-overlay-hider"},{Z:"div",A:"ytp-ce-expanding-overlay-background"},{Z:"div",A:"ytp-ce-expanding-overlay-content",
G:[{Z:"div",A:"ytp-ce-expanding-overlay-body",G:[{Z:"div",A:"ytp-ce-expanding-overlay-body-padding",G:[{Z:"div",A:"ytp-ce-merchandise-title",N:{dir:g.hi(U.title||"")},zJ:U.title},n,{Z:"div",A:"ytp-ce-merchandise-metadata",zJ:U.metadata},{Z:"a",O4:["ytp-ce-merchandise-goto","ytp-ce-link"],N:{href:I7(k,U.targetUrl),target:"_blank",tabindex:"-1"},zJ:U.callToAction}]}]}]}]},{Z:"div",A:"ytp-ce-expanding-image",N:tP(U)},{Z:"div",A:"ytp-ce-merchandise-invideo-cta-container",G:[{Z:"div",A:"ytp-ce-merchandise-invideo-cta",
zJ:U.callToAction||void 0}]}]},n=new g.l(k)}U.isPlaceholder&&g.F_(n.element,"ytp-ce-placeholder");return n},A52=function(k,U,n){function Z(){L(1)}
function C(){L(-1)}
U.listen("mouseenter",()=>{qn(k,U,n)});
U.listen("mouseleave",()=>{JP(k,U,n)});
k.player.U().B||U.listen("click",()=>{g.F_(U.element,"ytp-ce-element-hover")});
U.listen("click",F=>{HKm(k,n,F)});
U.listen("keypress",F=>{HKm(k,n,F)});
U.listen("focus",()=>{qn(k,U,n)});
U.listen("blur",()=>{JP(k,U,n)});
U.listen("touchstart",()=>{qn(k,U,n)});
var r=g.xC("ytp-ce-expanding-overlay-hider",U.element);r&&U.K(r,"touchstart",F=>{F.stopPropagation();g.Oe(U.element,"ytp-ce-element-hover");g.Oe(U.element,"ytp-ce-force-expand")});
U.listen("keydown",F=>{k.dM=F.keyCode===9&&!F.shiftKey});
const L=F=>{k.L+=F;k.L>0?(g.F_(U.element,"ytp-ce-force-expand"),e$(k,n.id,!0)):(g.Oe(U.element,"ytp-ce-force-expand"),g.Oe(U.element,"ytp-ce-element-hover"),e$(k,n.id,!1))};
r=F=>{F&&(U.listen("blur",()=>{F.style.display!="none"&&k.dM&&F.focus()}),U.K(F,"focus",Z),U.K(F,"blur",C))};
r(g.xC("ytp-sb-subscribe",U.element));r(g.xC("ytp-sb-unsubscribe",U.element));U.listen("focus",Z);U.listen("blur",C)},BF=function(k,U,n){function Z(){r||(C++,C===U.length&&(L.stop(),n&&n()))}
if(!U||U.length===0||pA(k))n&&n();else{U=RJV(k,U);var C=0,r=!1,L=new g.iX(()=>{r=!0;n&&n()},1E3,k);
L.start();for(k=0;k<U.length;k++)g.Gj(U[k],Z)}},tP=function(k){let U;
k.A5&&(U=k.A5.thumbnails);return V6b(U?U[U.length-1].url:null)},I7=function(k,U){k=k.player.U();
if(U){if(U.startsWith("//"))return k.protocol+":"+U;if(U.startsWith("/"))return g.Nq(k)+U}else return"";return U},V6b=function(k){return k?{style:"background-image: url("+k+")"}:{}},qn=function(k,U,n){g.L2(U.element,"ytp-ce-element-hover")||(n.type==="VIDEO"||n.type==="PLAYLIST"?g.F_(U.element,"ytp-ce-element-hover"):k.player.U().B?(new g.iX(()=>{g.F_(U.element,"ytp-ce-element-hover")},200)).start():g.F_(U.element,"ytp-ce-element-hover"),BF(k,n.nX),e$(k,n.id,!0))},JP=function(k,U,n){g.Oe(U.element,
"ytp-ce-element-hover");
g.Oe(U.element,"ytp-ce-force-expand");e$(k,n.id,!1)},HKm=function(k,U,n){if(U.targetUrl&&(!n||n.type!=="keypress"||n.keyCode===13)){for(var Z=n.target;Z&&!g.L2(Z,"ytp-ce-element");){g.L2(Z,"subscribe-label")&&PF(k,U);
if(g.L2(Z,"ytp-ce-channel-subscribe"))return;Z=Z.parentElement||null}if(!Z||g.L2(Z,"ytp-ce-element-hover")){n.preventDefault();n.stopPropagation();if(Z=k.B[U.id])JP(k,Z,U),Z.element.blur();if(n.ctrlKey||n.metaKey||U.jq==="new")PF(k,U),k.player.sendVideoStatsEngageEvent(17,void 0),k.player.pauseVideo(),n=g.De(I7(k,U.targetUrl)),n=g.BV(n),g.Ck(n,void 0,U.sessionData);else{const C=g.kD(k.player.U())||k.player.getVideoData().wm,r=()=>{var L=I7(k,U.targetUrl),F=U.sessionData,v=U.watchEndpoint;const O=
g.Qt(L);C&&O&&(O.v||O.list)?k.player.OQ(O.v,F,O.list,!1,void 0,v||void 0):g.Zn(L,F)};
PF(k,U,()=>{k.player.sendVideoStatsEngageEvent(17,r)})}}}},e$=function(k,U,n){k.j&&(n?k.W.show():k.W.hide());
for(const Z of Object.keys(k.B))Z!==U&&g.N(k.B[Z].element,"ytp-ce-element-shadow-show",n)},PF=function(k,U,n){BF(k,U.clickUrls,n);
(k=g.Tz())&&U.Q2&&g.L_(k,U.visualElement)},RJV=function(k,U){var n=k.player.getVideoData().clientPlaybackNonce;
k=k.player.getCurrentTime().toFixed(2);n={CPN:n,AD_CPN:n,MT:k};k=[];for(let Z=0;Z<U.length;Z++)k.push(hJ8(U[Z],n));return k},hJ8=function(k,U){return k.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,n=>{let Z=unescape(n);
Z=Z.substring(1,Z.length-1);return U[Z]?escape(U[Z]):n})},bK7=function(k){return typeof k==="string"?k:""},s0=function(k,U,n){for(const Z in U)if(U[Z]===k)return k;
return n},Yt=function(k){if(!k)return null;
var U=g.De(bK7(k.value));U=g.BV(U);if(!U)return null;const n=s0(k.target,zJp,"current");if(n==null)k=null;else{var Z=k.show_link_icon;k=new Qgx(U,n,Z==="true"||Z==="false"?Z==="true":!0,k.pause_on_navigation!=null?k.pause_on_navigation:!0)}return k},$sV=function(k){if(!k)return null;
const U=s0(k.type,K5V),n=s0(k.trigger,T8O);k=k.url;k=Array.isArray(k)&&k.length?k[0]:k;k=Yt(k?k:null);return U?new aQi(U,n,k):null},plx=function(k,U){return g.kB(k.action,U)},Du=function(k,U){k="background-image: url("+k+");";
const n=[];U&&n.push(U);return{Z:"div",A:"iv-card-image",N:{style:k},G:n}},WF=function(k){return k.customMessage?o7("div","iv-card-message",k.customMessage):""},j$=function(k){if(!k.metaInfo||k.metaInfo.length===0)return"";
const U=[];for(const n of k.metaInfo)U.push(o7("li","",n));return{Z:"ul",A:"iv-card-meta-info",G:U}},S$=function(k,U,n,Z){if(Z)for(const C of U)k.S(C,Z,n.id,n.sessionData,n.Pu.click,5)},o7=function(k,U,n){U?typeof U==="string"?U={"class":U}:Array.isArray(U)&&(U={"class":U.join(" ")}):U={};
U.dir=g.hi(n);return{Z:k,N:U,zJ:n}},N87=function(k){if(!k.customMessage)return"";
const U=["iv-card-action","iv-card-primary-link"],n={};k.X1&&(U.push("iv-card-action-icon"),n.style="background-image: url("+k.X1+");");n.dir=g.hi(k.customMessage);const Z=[{Z:"span",zJ:k.customMessage}];k.showLinkIcon&&(Z.push("\u00a0"),Z.push({Z:"span",A:"iv-card-link-icon"}));return{Z:"div",O4:U,N:n,G:Z}},t6V=function(k){var U;
(U=k)&&!(U=k.length>1?k.charAt(0)==="/"&&k.charAt(1)!=="/":k==="/")&&(U=k.replace(/^(https?:)?\/\//,"").split("/",1),U=!U||U.length<1||!U[0]?[]:U[0].toLowerCase().split(".").reverse(),U=U[0]==="com"&&U[1]==="youtube"||U[0]==="be"&&U[1]==="youtu");return U?k.indexOf("/redirect?")===-1:!1},IQY=function(k,U){return U?U:t6V(k)?"current":"new"},G1=function(k,U,n,Z,C,r,L){k.context.S.listen(U,"click",F=>{k.aQ(n,Z,C,r||[],L||0,F)});
k.context.S.listen(U,"touchstart",()=>{k.Fo=!1});
k.context.S.listen(U,"touchmove",()=>{k.Fo=!0})},qxO=function(k){if(g.e(k,g.BC)?.url)return g.e(k,g.BC).url;
if((k=g.e(k,g.A$))&&k.videoId){let U="/watch?v="+k.videoId;k.playlistId&&(U+="&list="+k.playlistId);k.index&&(U+="&index="+k.index);k.startTimeSeconds&&(U+="&t="+k.startTimeSeconds);return U}return null},fA=function(k,U,n){return{uO:(k.impressionLoggingUrlsV2s||[]).map(Z=>Z.baseUrl||""),
click:(n.loggingUrls||[]).map(Z=>Z.baseUrl||""),
close:(U.dismissLoggingUrlsV2s||[]).map(Z=>Z.baseUrl||""),
Du:(U.impressionLoggingUrlsV2s||[]).map(Z=>Z.baseUrl||""),
CM:(U.clickLoggingUrlsV2s||[]).map(Z=>Z.baseUrl||"")}},lp=function(k,U){if(U.onClickCommand&&g.e(U.onClickCommand,g.BY6)?.targetId==="engagement-panel-error-corrections"){k.Y=U;
var n=!0}else n=!1;if(!n||J5p(k,U))if(n=eJO(k,U)){var Z={OJ:U,xp:n.element,Ly:!1};if(U.onClickCommand)k.O.C("web_infocards_teaser_show_logging_fix")&&(k.xo||PAs(k),Mn(k,U.id),n=k.findLastIndex(Z),g.db(k.cards,n,0,Z));else{k.isInitialized||B8x(k);Mn(k,U.id);const C=k.findLastIndex(Z);g.db(k.cards,C,0,Z);n.E4(k.B,C);k.Wy()}U.autoOpen?k.addCueRange(U.startMs,0x8000000000000,U.id,()=>{k.j||(k.S=Z,y1(k),sgE(k,Z),cF(k,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(n=k.context.O.getCurrentTime()*1E3,n<5E3&&n>U.startMs&&
Yxb(k,Z),k.addCueRange(U.startMs,U.startMs+1,U.id,()=>{Yxb(k,Z)}),y1(k))}},m2=function(k){k.j&&(k.bL.hide(),k.pN.B(),g.Oe(k.context.O.getRootNode(),g.ge.IV_DRAWER_OPEN),k.j=!1,V1(k.O),k.V&&k.V.stop(),k.V=new g.iX(()=>{k.IQ&&(k.IQ.focus(),k.IQ=null)},330),k.V.start())},Ds_=function(k,U){U=U.data;
U.autoOpenMs&&k.addCueRange(U.autoOpenMs,0x8000000000000,"",()=>{cF(k,"YOUTUBE_DRAWER_AUTO_OPEN")});
U.autoCloseMs&&k.addCueRange(U.autoCloseMs,0x8000000000000,"",()=>{m2(k)});
const n=U.headerText;g.d8(k.Y$,n);k.W&&(k.O.C("player_tooltip_data_title_killswitch")?k.W.setAttribute("title",n):k.W.setAttribute("data-tooltip-title",n));U.eventId&&(k.eventId=U.eventId);k.eE=g.bf(U.trackingParams);k.X=g.bf(U.closeTrackingParams);k.sJ=g.bf(U.iconTrackingParams)},xt=function(k,U,n){let Z=-1,C=-1;
for(let r=0;r<k.length;r++){if(k[r].height===U||k[r].width===n)return k[r];((k[r].height||0)<U||(k[r].width||0)<n)&&(Z<0||(k[Z].height||0)<(k[r].height||0)||(k[Z].width||0)<(k[r].width||0))?Z=r:((k[r].height||0)>=U||(k[r].width||0)>=n)&&(C<0||(k[C].height||0)>(k[r].height||0)||(k[C].width||0)>(k[r].width||0))&&(C=r)}return k[C>=0?C:Z]},k$=function(k,U,n,Z){return{feature:n.feature?n.feature:"cards",
src_vid:k.context.videoData.videoId,annotation_id:U,ei:k.context.videoData.eventId||"",itct:Z.trackingParams||""}},orb=function(k,U){const n=U.cardId?U.cardId:`cr:${k.L}`;
var Z=k.O.U().experiments.iL("enable_error_corrections_infocard_web_client");if(!U.content&&U.teaser.simpleCardTeaserRenderer&&Z){Z=U.teaser.simpleCardTeaserRenderer;var C=U.icon?U.icon.infoCardIconRenderer:null;if(Z.channelAvatar&&Z.channelAvatar.thumbnails&&Z.channelAvatar.thumbnails.length>0)var r=xt(Z.channelAvatar.thumbnails,22,22).url;U={id:n,timestamp:k.L,type:"simple",teaserText:g.E8(Z.message),teaserDurationMs:Number(U.cueRanges[0].teaserDurationMs),startMs:Number(U.cueRanges[0].startCardActiveMs),
autoOpen:!!U.autoOpen,sessionData:{},sponsored:!1,Pu:{},Nh:null,K2:Z.trackingParams?g.bf(Z.trackingParams):null,sJ:C&&C.trackingParams?g.bf(C.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,X1:null,title:"",customMessage:"",url:null,onClickCommand:Z.onTapCommand||null,Wb:r};lp(k,U)}else if(U.content?.simpleCardContentRenderer){if(!U.cueRanges.length)return;r=U.content?.simpleCardContentRenderer;Z=U.teaser.simpleCardTeaserRenderer;C=U.icon?U.icon.infoCardIconRenderer:null;U={id:n,
timestamp:k.L,type:"simple",teaserText:g.E8(Z.message),teaserDurationMs:Number(U.cueRanges[0].teaserDurationMs),startMs:Number(U.cueRanges[0].startCardActiveMs),autoOpen:!!U.autoOpen,sessionData:k$(k,n,U,r),sponsored:!1,Pu:fA(r,Z,r.command),Nh:r.trackingParams?g.bf(r.trackingParams):null,K2:Z.trackingParams?g.bf(Z.trackingParams):null,sJ:C&&C.trackingParams?g.bf(C.trackingParams):null,imageUrl:xt(r.image.thumbnails,290,290).url,displayDomain:r.displayDomain?g.E8(r.displayDomain):null,showLinkIcon:!!r.showLinkIcon,
X1:null,title:r.title?g.E8(r.title):"",customMessage:r.callToAction?g.E8(r.callToAction):"",url:g.e(r.command,g.BC).url?Yt({pause_on_navigation:!k.context.videoData.isLivePlayback,target:"new",value:g.e(r.command,g.BC).url}):null,onClickCommand:null};lp(k,U)}else if(U.content?.collaboratorInfoCardContentRenderer){if(!U.cueRanges.length)return;r=U.content?.collaboratorInfoCardContentRenderer;Z=U.teaser.simpleCardTeaserRenderer;C=U.icon?U.icon.infoCardIconRenderer:null;U={id:n,timestamp:k.L,type:"collaborator",
teaserText:g.E8(Z.message),teaserDurationMs:Number(U.cueRanges[0].teaserDurationMs),startMs:Number(U.cueRanges[0].startCardActiveMs),autoOpen:!!U.autoOpen,sessionData:k$(k,n,U,r),sponsored:!1,Pu:fA(r,Z,r.endpoint),Nh:r.trackingParams?g.bf(r.trackingParams):null,K2:Z.trackingParams?g.bf(Z.trackingParams):null,sJ:C&&C.trackingParams?g.bf(C.trackingParams):null,channelId:g.e(r.endpoint,g.En).browseId,customMessage:r.customText?g.E8(r.customText):null,profileImageUrl:xt(r.channelAvatar.thumbnails,290,
290).url,title:r.channelName?g.E8(r.channelName):"",metaInfo:[r.subscriberCountText?g.E8(r.subscriberCountText):""],url:Yt({pause_on_navigation:!k.context.videoData.isLivePlayback,target:"new",value:g.e(r.endpoint,g.En).canonicalBaseUrl?g.e(r.endpoint,g.En).canonicalBaseUrl:`/channel/${g.e(r.endpoint,g.En).browseId}`}),onClickCommand:null};lp(k,U)}else if(U.content?.playlistInfoCardContentRenderer){if(!U.cueRanges.length)return;r=U.content?.playlistInfoCardContentRenderer;Z=U.teaser.simpleCardTeaserRenderer;
C=U.icon?U.icon.infoCardIconRenderer:null;U={id:n,timestamp:k.L,type:"playlist",teaserText:g.E8(Z.message),teaserDurationMs:Number(U.cueRanges[0].teaserDurationMs),startMs:Number(U.cueRanges[0].startCardActiveMs),autoOpen:!!U.autoOpen,sessionData:k$(k,n,U,r),sponsored:!1,Pu:fA(r,Z,r.action),Nh:r.trackingParams?g.bf(r.trackingParams):null,K2:Z.trackingParams?g.bf(Z.trackingParams):null,sJ:C&&C.trackingParams?g.bf(C.trackingParams):null,Zx:xt(r.playlistThumbnail.thumbnails,258,290).url,customMessage:r.customMessage?
g.E8(r.customMessage):null,playlistVideoCount:g.E8(r.playlistVideoCount),title:r.playlistTitle?g.E8(r.playlistTitle):"",metaInfo:[r.channelName?g.E8(r.channelName):"",r.videoCountText?g.E8(r.videoCountText):""],url:Yt({pause_on_navigation:!k.context.videoData.isLivePlayback,target:"new",value:qxO(r.action)}),onClickCommand:null};lp(k,U)}else if(U.content?.videoInfoCardContentRenderer){if(!U.cueRanges.length)return;r=U.content?.videoInfoCardContentRenderer;Z=U.teaser.simpleCardTeaserRenderer;C=U.icon?
U.icon.infoCardIconRenderer:null;U={id:n,timestamp:k.L,type:"video",teaserText:g.E8(Z.message),teaserDurationMs:Number(U.cueRanges[0].teaserDurationMs),startMs:Number(U.cueRanges[0].startCardActiveMs),autoOpen:!!U.autoOpen,sessionData:k$(k,n,U,r),sponsored:!1,Pu:fA(r,Z,r.action),Nh:r.trackingParams?g.bf(r.trackingParams):null,K2:Z.trackingParams?g.bf(Z.trackingParams):null,sJ:C&&C.trackingParams?g.bf(C.trackingParams):null,Zx:xt(r.videoThumbnail.thumbnails,258,290).url,videoDuration:r.lengthString?
g.E8(r.lengthString):null,customMessage:r.customMessage?g.E8(r.customMessage):null,title:r.videoTitle?g.E8(r.videoTitle):"",metaInfo:[r.channelName?g.E8(r.channelName):"",r.viewCountText?g.E8(r.viewCountText):""],isLiveNow:!!r.badge,url:Yt({pause_on_navigation:!k.context.videoData.isLivePlayback,target:"new",value:qxO(r.action)}),onClickCommand:null};lp(k,U)}k.L++},W5Y=function(k,U){return g.kB(k.cards,n=>n.OJ.id===U)},y1=function(k){g.N(k.O.getRootNode(),"ytp-cards-shopping-active",jgO(k))},Mn=function(k,
U){if(U=W5Y(k,U))U===k.S&&(k.S=null),k.O.removeCueRange(U.OJ.id),g.Ex(U.xp),g.FO(k.cards,U),k.Wy(),y1(k)},cF=function(k,U,n){if(!k.j){k.bL.show();
k.TJ=new g.iX(()=>{g.F_(k.context.O.getRootNode(),g.ge.IV_DRAWER_OPEN)},0);
k.TJ.start();k.pN.K(k.B,"mousewheel",C=>{k.By.start();C.preventDefault();C=C||window.event;let r=0;C.type=="MozMousePixelScroll"?r=0==(C.axis==C.HORIZONTAL_AXIS)?C.detail:0:window.opera?r=C.detail:r=C.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?C.wheelDeltaY/-30:C.wheelDeltaY/-1.2:C.wheelDelta/-1.6:C.wheelDeltaY/-3;if(C=r)k.B.scrollTop+=C});
k.j=!0;var Z=g.Tz();Z&&k.eE&&k.X&&g.C_(Z,[k.eE,k.X]);U={TRIGGER_TYPE:U};for(const C of k.cards)C.Ly||(C.Ly=!0,Sxx(k.context.logger,C.OJ.Pu.uO,U)),Z&&g.C_(Z,[C.OJ.Nh]);V1(k.O);n&&(k.V=new g.iX(()=>{k.IQ=k.W;k.h8.focus()},330),k.V.start())}},B8x=function(k){g.v$(k.j5(),[g.ge.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.$Z(k.O,k.J,5);k.n$();k.W=g.xC("ytp-cards-button",k.O.getRootNode());k.h8=g.xC("iv-drawer-close-button",k.J);k.isInitialized=!0},PAs=function(k){k.dM.push(g.rk("iv-teaser-shown",k.V3,k));
k.dM.push(g.rk("iv-teaser-hidden",k.PV,k));k.dM.push(g.rk("iv-teaser-clicked",k.e5,k));k.xo=!0},J5p=function(k,U){k.Y=U;
var n=k.O.getVideoData();if(!n)return!1;n=g.x5(n);if(n?.markersMap)for(let C=0;n?.markersMap.length>C;C++){var Z=n?.markersMap[C];if(Z.key==="ERROR_CORRECTION_MARKERS"&&(Z=Z.value?.markers)&&Z.length>0)return U.startMs=g.e(Z[0],g.Oha)?.timeRangeStartMillis||0,k.Y=null,!0}return!1},eJO=function(k,U){switch(U.type){case "simple":k=k.x$;
var n=U.displayDomain?{Z:"div",A:"iv-card-image-text",zJ:U.displayDomain}:void 0;var Z=N87(U);n={Z:"div",O4:["iv-card"],G:[{Z:"a",A:"iv-click-target",N:{href:U.url?U.url.S()||"":""},G:[Du(U.imageUrl,n),{Z:"div",A:"iv-card-content",G:[o7("h2",void 0,U.title),Z]}]}]};n=new g.l(n);S$(k,g.lC("iv-click-target",n.element),U,U.url);U=n;break;case "collaborator":k=k.x$;n={Z:"div",O4:["iv-card","iv-card-channel"],G:[{Z:"a",O4:["iv-click-target"],N:{href:U.url.S()||"","data-ytid":U.channelId},G:[Du(U.profileImageUrl),
{Z:"div",A:"iv-card-content",G:[WF(U),{Z:"h2",A:"iv-card-primary-link",zJ:U.title},j$(U)]}]}]};n=new g.l(n);S$(k,g.lC("iv-click-target",n.element),U,U.url);U=n;break;case "playlist":k=k.x$;n={Z:"div",O4:["iv-card","iv-card-playlist"],G:[{Z:"a",A:"iv-click-target",N:{href:U.url.S()||""},G:[Du(U.Zx,{Z:"div",A:"iv-card-image-overlay",G:[{Z:"span",A:"iv-card-playlist-video-count",zJ:U.playlistVideoCount}]}),{Z:"div",A:"iv-card-content",G:[WF(U),o7("h2","iv-card-primary-link",U.title),j$(U)]}]}]};n=new g.l(n);
S$(k,g.lC("iv-click-target",n.element),U,U.url);U=n;break;case "productListing":k=k.x$;var C=U.offers.length!=0;n=["iv-card"];Z="";var r=N87(U);C&&(n.push("iv-card-product-listing"),Z="iv-card-primary-link",r=U.offers[0],C=[],r.price&&C.push({Z:"div",A:"iv-card-offer-price",zJ:r.price}),r.merchant&&C.push({Z:"div",A:"iv-card-offer-merchant",zJ:r.merchant}),r={Z:"div",G:C});C=U.url?U.url.S()||"":"";n={Z:"div",O4:n,N:{tabindex:"0"},G:[{Z:"a",O4:["iv-card-image","iv-click-target"],N:{style:"background-image: url("+
U.imageUrl+");",href:C,"aria-hidden":"true",tabindex:"-1"}},{Z:"div",A:"iv-card-content",G:[U.sponsored?{Z:"div",A:"iv-card-sponsored",G:["Sponsored",{Z:"div",A:"iv-ad-info-container",G:[{Z:"div",A:"iv-ad-info",zJ:"{{adInfo}}"},{Z:"div",A:"iv-ad-info-icon-container",G:[{Z:"div",A:"iv-ad-info-icon"},{Z:"div",A:"iv-ad-info-callout"}]}]}]}:"",{Z:"a",A:"iv-click-target",N:{href:C},G:[o7("h2",Z,U.title),r]}]}]};n=new g.l(n);Z=g.Ox("span");g.d8(Z,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
n.setContent(Z,"adInfo");S$(k,g.lC("iv-click-target",n.element),U,U.url);U=n;break;case "video":k=k.x$;n=U.isLiveNow?{Z:"span",O4:["yt-badge","yt-badge-live"],zJ:"LIVE NOW"}:null;n={Z:"div",O4:["iv-card","iv-card-video"],G:[{Z:"a",A:"iv-click-target",N:{href:U.url?.S()||""},G:[Du(U.Zx,U.videoDuration?{Z:"span",A:"iv-card-video-duration",zJ:U.videoDuration}:void 0),{Z:"div",A:"iv-card-content",G:[WF(U),o7("h2","iv-card-primary-link",U.title),j$(U),n]}]}]};n=new g.l(n);S$(k,g.lC("iv-click-target",n.element),
U,U.url);U=n;break;default:return null}return U},Yxb=function(k,U){if(!g.L2(k.O.getRootNode(),"ytp-cards-teaser-shown")){if(k.S!==U){var n=g.Tz(),Z=k.S?k.S.OJ.sJ:k.sJ;
n&&Z&&g.ry(n,[Z]);k.S=U;y1(k)}(n=k.isInitialized&&k.j5().style.display=="none")||(n=k.context.O.getPlayerState(),Z=n===0&&k.context.O.getCurrentTime()===0,n=!(n===1||n===3||Z));n||U.OJ.teaserDurationMs&&k.O.JG(!0,{teaserText:U.OJ.teaserText,durationMs:U.OJ.teaserDurationMs,onClickCommand:U.OJ.onClickCommand,Wb:U.OJ.Wb??null});k.GJ.isActive()||((!k.j||!k.By.isActive()&&k.V$)&&sgE(k,U),k.GJ.start(910+U.OJ.teaserDurationMs))}},jgO=function(k){return k.S?k.S.OJ.type==="productListing":k.O.C("enable_wn_infocards")?
!!k.cards?.length&&g.mB(k.cards,U=>U.OJ.type==="productListing"):g.mB(k.cards,U=>U.OJ.type==="productListing")},sgE=function(k,U){k.D.Bc?(U=new z1([0,
k.B.scrollTop],[0,U.xp.offsetTop],600,wls),k.context.j.listen(U,"animate",n=>{k.B.scrollTop=n.y}),k.context.j.listen(U,"finish",n=>{k.B.scrollTop=n.y}),U.play()):(k.D.Uj(!0),k.B.scrollTop=U.xp.offsetTop,k.D.Uj(!1))},i8=function(k){return k.S&&k.S.OJ?k.S.OJ:k.cards[0]&&k.cards[0].OJ?k.cards[0].OJ:null},GK8=function(k){const U=k.annotation.data;
"start_ms"in U&&"end_ms"in U&&k.addCueRange(Number(U.start_ms),Number(U.end_ms),k.annotation.id,()=>{k.show()},()=>{k.hide()})},fQO=function(k,U){var n=nrV(U).width;
g.S6(U,n);n=new KA(U,[n,U.offsetTop],[n-n,U.offsetTop],200,OK8);g.K(k,n);k.context.j.listen(n,"begin",()=>{g.kL(U,!0)});
n.play()},U3=function(k,U,n){n.stopPropagation();
M6V(k);y58(k,U);k.S.focus()},c57=function(k){const U=k.annotation.data;
if(k.annotation.style==="cta")var n=6;else if(k.annotation.style==="video"||k.annotation.style==="playlist")n=7;k.V=U.collapsedelay_ms||k.V;const Z=["iv-promo","iv-promo-inactive"];k.j5().setAttribute("aria-hidden","true");k.j5().setAttribute("aria-label","Promotion");k.j5().tabIndex=0;const C=k.annotation.Hn();let r;var L=U.image_url;L&&(r=k.createElement({Z:"div",O4:["iv-promo-img","iv-click-target"]}),L=k.createElement({Z:"img",N:{src:L,"aria-hidden":"true"}}),r.appendChild(L),U.video_duration&&
!U.is_live?(L=k.createElement({Z:"span",A:"iv-promo-video-duration",zJ:U.video_duration}),r.appendChild(L)):U.playlist_length&&(L=k.createElement({Z:"span",A:"iv-promo-playlist-length",zJ:U.playlist_length.toString()}),r.appendChild(L)),C&&G1(k,r,C,k.annotation.id,U.session_data,void 0,n));C?(L=k.createElement({Z:"a",A:"iv-promo-txt"}),g.jp(L,C.S()),k.S=L):k.S=k.createElement({Z:"div",A:"iv-promo-txt"});let F,v,O,w;switch(k.annotation.style){case "cta":case "website":F=k.createElement({Z:"p",G:[{Z:"strong",
zJ:U.text_line_1}]});v=k.createElement({Z:"p",G:[{Z:"span",A:"iv-promo-link",zJ:U.text_line_2}]});if(L=U.text_line_3)Z.push("iv-promo-website-card-cta-redesign"),O=k.createElement({Z:"button",O4:["iv-promo-round-expand-icon","ytp-button"]}),L=k.createElement({Z:"button",O4:["iv-button","iv-promo-button"],G:[{Z:"span",A:"iv-button-content",zJ:L}]}),w=k.createElement({Z:"div",A:"iv-promo-button-container"}),w.appendChild(L),C&&G1(k,k.j5(),C,k.annotation.id,U.session_data,void 0,n);g.F_(k.S,"iv-click-target");
C&&G1(k,k.S,C,k.annotation.id,U.session_data,void 0,n);break;case "playlist":case "video":F=k.createElement({Z:"p",G:[{Z:"span",zJ:U.text_line_1}]}),v=k.createElement({Z:"p",G:[{Z:"strong",zJ:U.text_line_2}]}),U.is_live&&(F=v,v=k.createElement({Z:"span",O4:["yt-badge","iv-promo-badge-live"],zJ:"LIVE NOW"})),g.F_(k.S,"iv-click-target"),C&&G1(k,k.S,C,k.annotation.id,U.session_data,void 0,n),Z.push("iv-promo-video")}F&&k.S.appendChild(F);v&&k.S.appendChild(v);k.L.appendChild(k.S);w&&k.L.appendChild(w);
n=k.createElement({Z:"div",A:"iv-promo-actions"});k.B=k.createElement({Z:"button",O4:["iv-promo-expand","ytp-button"]});k.B.title="Expand";k.context.S.listen(k.B,"click",u=>{U3(k,5E3,u)});
n.appendChild(k.B);g.kL(k.B,!1);k.context.S.listen(k.j5(),"mouseover",k.By,k);k.context.S.listen(k.j5(),"mouseout",k.x$,k);k.context.S.listen(k.j5(),"touchend",u=>{U3(k,5E3,u)});
k.j=k.createElement({Z:"button",O4:["iv-promo-close","ytp-button"]});k.j.title="Close";k.context.S.listen(k.j,"click",k.annotation.style==="cta"&&U.text_line_3?k.Y:k.dM,k);n.appendChild(k.j);g.v$(k.j5(),Z);r&&(g.uA(k.j5(),r),O&&r.appendChild(O));g.uA(k.j5(),k.L);g.uA(k.j5(),n)},nc=function(k){k.J&&(g.Vs.clearTimeout(k.J),k.J=null)},M6V=function(k){k.W.stop();
k.isCollapsed&&(g.wp(k.j5(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),k.isCollapsed=!1,k.S&&k.S.removeAttribute("aria-hidden"),g.kL(k.B,!1),g.kL(k.j,!0))},y58=function(k,U){k.J||(k.J=g.Oh(function(){nc(this);
lQO(this)},U,k))},lQO=function(k){k.isCollapsed||k.X||k.J||(g.F_(k.j5(),"iv-promo-collapsed"),k.isCollapsed=!0,k.W.start())},Sxx=function(k,U,n){U&&(n?Zz(k,U.map(Z=>g.en(Z,n))):Zz(k,U))},Zz=function(k,U,n,Z){let C=1,r=void 0,L=-1;
if(n){let F=!1;r=()=>{C--;C||F||(clearTimeout(L),F=!0,n())};
L=setTimeout(()=>{F=!0;n()},1E3)}for(const F of U||[])C++,g.Gj(F,r);
Z&&(C++,Z!==0&&k.O.sendVideoStatsEngageEvent(Z,r))},ms7=function(k){return k==="annotation-editor"||k==="live-dashboard"},xsO=function(k){k.J&&(k.player.removeEventListener("videodatachange",k.J),k.J=null)},kVO=function(k){k=k.createElement({Z:"div",
O4:["annotation","annotation-type-custom"]});g.kL(k,!1);return k},rO=function(k,U){var n=!1,Z=U.getElementsByTagName("annotations");
if(Z&&!(Z.length<1)&&(Z=Z[0].getAttribute("itct"))){var C=g.Tz();if(C){var r=g.Kf();r&&g.kU(g.yi)(void 0,C,r,[g.bf(Z)])}}U=U.getElementsByTagName("annotation");for(Z=0;Z<U.length;Z++){var L=i0p(k,U[Z]);C=null;try{a:{if(!L){C=null;break a}var F=L.id;r=/.+/;const E=typeof F==="string"&&r!=null&&F!=null&&F.match(r)?F:"",V=s0(L.type,UP7),Q=s0(L.style,nLm),p=bK7(L.data),I=p.length!==0?JSON.parse(p):{};b:{var v=L.action;r=$sV;if(v==null){var O=null;break b}if(g.Qs(v)){L=[];for(const J of v){const P=r(J);
P&&L.push(P)}O=L;break b}const t=r(v);O=t?[t]:[]}r=O;C=E&&V?new Z0E(E,V,Q,r,I):null}}catch(E){}if(C)if(C.type==="branding"||C.type==="promotion"){r=k;L=C;var w=kVO(r),u=null;switch(L.type){case "branding":if(r.player.U().Nf)break;r.player.C("web_player_overlay_positioned_layout")?(w.setAttribute("data-overlay-order","11"),r.player.cJ(w,4,!0)):r.B.element.appendChild(w);u=new C_Y(w,Cc(r),L);break;case "promotion":g.$Z(r.player,w,4),u=new rKb(w,Cc(r),L)}u&&u.SE();if(r=u)g.K(k,r),k.V[C.id]=r}else if(C.type===
"card"||C.type==="drawer"){k.S||(k.S=Ld2(k),g.K(k,k.S));if(C.type==="card"){w=k.S;var X=(n=C)&&n.data&&n.data.card_type;C=n.data;if(X)switch(r=C.tracking||{},r={uO:r.impression,click:r.click,close:r.close,Du:r.teaser_impression,CM:r.teaser_click},L=C.tracking_params||{},u=null,X){case "collaborator":n={id:n.id,timestamp:C.timestamp||0,type:C.card_type,teaserText:C.teaser_text,teaserDurationMs:C.teaser_duration_ms,startMs:C.start_ms,autoOpen:C.auto_open||!1,sessionData:C.session_data||{},sponsored:C.sponsored||
!1,Pu:r,Nh:L.card?g.bf(L.card):null,K2:L.teaser?g.bf(L.teaser):null,sJ:L.icon?g.bf(L.icon):null,channelId:C.channel_id,customMessage:C.custom_message?C.custom_message:null,profileImageUrl:C.image_url,title:C.title,metaInfo:C.meta_info,url:Yt({pause_on_navigation:C.pause_on_navigation,target:C.target||"new",value:C.url}),onClickCommand:null};lp(w,n);break;case "playlist":n={id:n.id,timestamp:C.timestamp||0,type:C.card_type,teaserText:C.teaser_text,teaserDurationMs:C.teaser_duration_ms,startMs:C.start_ms,
autoOpen:C.auto_open||!1,sessionData:C.session_data||{},sponsored:C.sponsored||!1,Pu:r,Nh:L.card?g.bf(L.card):null,K2:L.teaser?g.bf(L.teaser):null,sJ:L.icon?g.bf(L.icon):null,Zx:C.image_url,playlistVideoCount:C.playlist_video_count,customMessage:C.custom_message?C.custom_message:null,title:C.title,metaInfo:C.meta_info,url:Yt({pause_on_navigation:C.pause_on_navigation,target:C.target||"new",value:C.url}),onClickCommand:null};lp(w,n);break;case "productListing":C.signin_url&&(u=Yt({target:"current",
value:C.signin_url}));X=[];const E=C.offers||[];for(let V=0;V<E.length;V++)X.push(new Fd7(g.gw(E[V].merchant),g.gw(E[V].price)));n={id:n.id,timestamp:C.timestamp||0,type:C.card_type,teaserText:C.teaser_text,teaserDurationMs:C.teaser_duration_ms,startMs:C.start_ms,autoOpen:C.auto_open||!1,sessionData:C.session_data||{},sponsored:C.sponsored||!1,Pu:r,Nh:L.card?g.bf(L.card):null,K2:L.teaser?g.bf(L.teaser):null,sJ:L.icon?g.bf(L.icon):null,imageUrl:C.image_url,displayDomain:C.display_domain?C.display_domain:
null,showLinkIcon:!!C.show_link_icon,X1:C.button_icon_url?C.button_icon_url:null,title:C.title,customMessage:C.custom_message?C.custom_message:null,url:Yt({pause_on_navigation:C.pause_on_navigation,target:C.target||"new",value:C.url}),ZWg:u,Ik$:C.signin_title?C.signin_title:void 0,W_Q:C.signin_message?C.signin_message:void 0,offers:X,onClickCommand:null};lp(w,n);break;case "simple":n={id:n.id,timestamp:C.timestamp||0,type:C.card_type,teaserText:C.teaser_text,teaserDurationMs:C.teaser_duration_ms,
startMs:C.start_ms,autoOpen:C.auto_open||!1,sessionData:C.session_data||{},sponsored:C.sponsored||!1,Pu:r,Nh:L.card?g.bf(L.card):null,K2:L.teaser?g.bf(L.teaser):null,sJ:L.icon?g.bf(L.icon):null,imageUrl:C.image_url,displayDomain:C.display_domain?C.display_domain:null,showLinkIcon:!!C.show_link_icon,X1:C.button_icon_url?C.button_icon_url:null,title:C.title,customMessage:C.custom_message?C.custom_message:null,url:Yt({pause_on_navigation:C.pause_on_navigation,target:C.target||"new",value:C.url}),onClickCommand:null};
lp(w,n);break;case "video":n={id:n.id,timestamp:C.timestamp||0,type:C.card_type,teaserText:C.teaser_text,teaserDurationMs:C.teaser_duration_ms,startMs:C.start_ms,autoOpen:C.auto_open||!1,sessionData:C.session_data||{},sponsored:C.sponsored||!1,Pu:r,Nh:L.card?g.bf(L.card):null,K2:L.teaser?g.bf(L.teaser):null,sJ:L.icon?g.bf(L.icon):null,Zx:C.image_url,videoDuration:C.video_duration||null,customMessage:C.custom_message?C.custom_message:null,title:C.title,metaInfo:C.meta_info,isLiveNow:!!C.is_live_now,
url:Yt({pause_on_navigation:C.pause_on_navigation,target:C.target||"new",value:C.url}),onClickCommand:null},lp(w,n)}}else Ds_(k.S,C);n=!0}}n&&(V1(k.player),k.D())},vLi=function(k){const U=k.player.U();
k=k.player.getVideoData();return(U.annotationsLoadPolicy||k.annotationsLoadPolicy)===1&&!k.k0||U.eE.get(k.videoId)||k.oi()||g.lT(k)?!0:!1},O0m=function(k,U){U=!U.isCued()&&!U.S(1024);
k.B.Uj(U);k.j.Uj(U)},X_i=function(k,U){const n=U.videoId;
var Z=r=>{var L=k.loadNumber;k.L=null;k.loaded&&k.loadNumber===L&&k.player.getVideoData().videoId===n&&(r=g.YX(r)&&r.responseXML?r.responseXML:null)&&(rO(k,r),g.F_(k.player.getRootNode(),"iv-module-loaded"))};
g.TW()&&(Z=w_s(k,Z));const C={format:"XML",onFinish:Z,onError:()=>{k.L=null},
urlParams:{}};U.isPharma&&(C.urlParams.pharma="1");C.method="POST";C.withCredentials=!0;(Z=k.player.U().eE.get(n))&&ud7(C,Z);Z=Z&&Z.ZB;if(!U.wC||Z)k.J=()=>{if(!k.Y)k.onVideoDataChange(C);const r=k.player.getVideoData();r?.ef()&&!k.dM&&gL7(k,r)},k.player.addEventListener("videodatachange",k.J)},Lc=function(k,U){var n=!1;
k.S||(k.S=Ld2(k),g.K(k,k.S));for(var Z of U.cards||[])Z.cardRenderer&&(orb(k.S,Z.cardRenderer),n=!0);n&&(k.player.getVideoData()?.ef()||(n=k.S,Z=U.headerText?g.E8(U.headerText):"",g.d8(n.Y$,Z),n.W&&(n.O.C("player_tooltip_data_title_killswitch")?n.W.setAttribute("title",Z):n.W.setAttribute("data-tooltip-title",Z)),n.context.videoData.eventId&&(n.eventId=n.context.videoData.eventId),n.eE=U.trackingParams?g.bf(U.trackingParams):null,n.X=U.closeButton.infoCardIconRenderer.trackingParams?g.bf(U.closeButton.infoCardIconRenderer.trackingParams):
null,n.sJ=U.icon.infoCardIconRenderer.trackingParams?g.bf(U.icon.infoCardIconRenderer.trackingParams):null,k.D()),V1(k.player))},gL7=function(k,U){if(U=U.getWatchNextResponse()?.cards?.cardCollectionRenderer)k.dM=!0,Lc(k,U),U.headerText&&k.L1&&(U=g.E8(U.headerText),k.player.C("player_tooltip_data_title_killswitch")?k.L1.setAttribute("title",U):k.L1.setAttribute("data-tooltip-title",U))},w_s=function(k,U){return(...n)=>{k.LN()||k.SE.push(g.Sn.y7(()=>{U(...n)}))}},ud7=function(k,U){k.method="POST";
k.postParams=k.postParams||{};U.ZB&&(k.postParams.ic_coll=U.ZB);U.x8&&(k.postParams.ic_track=U.x8)},i0p=function(k,U){const n={};
for(var Z of U.attributes)n[Z.name]=Z.nodeValue;for(Z=0;Z<U.childNodes.length;Z++){var C=U.childNodes[Z];if(!g.TN(C)||C.nodeType!=1)continue;var r=void 0;if(n[C.tagName])r=n[C.tagName];else if(C.tagName==="data"){C.childNodes.length>0&&(r=C.childNodes[0].nodeValue,n[C.tagName]=typeof r==="string"?r.trim():r);continue}else r=[],n[C.tagName]=r;C&&C.tagName==="TEXT"?C.childNodes.length===1&&C.childNodes[0].nodeType===3?r.push(C.childNodes[0].nodeValue):r.push(""):C&&r.push(i0p(k,C))}return n},Cc=function(k){if(!k.X){const U=
new ELO(k);
g.K(k,U);const n=new g.XL(k);g.K(k,n);k.X=new AKb(U,n,k.player.U(),k.player.getVideoData(),k.logger,k.player,k.TN)}return k.X},dP2=function(k){const U=k.player.getVideoData();
if(U.Yz){var n=k.player.U().eE.get(U.videoId);if(n){var Z={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:(C,r,L)=>{C=k.loadNumber;r=U.videoId;k.loaded&&k.loadNumber===C&&k.player.getVideoData().videoId===r&&(L=g.YX(L)&&L.responseXML?L.responseXML:null)&&rO(k,L)}};
g.TW()&&(Z.onFinish=w_s(k,Z.onFinish));Z.postParams={ic_only:"1"};ud7(Z,n);k.Y=!0;g.xX(U.Yz,Z)}}},Ld2=function(k){const U=new g.l({Z:"div"});
g.kL(U.element,!1);const n=new V_B(k.player,U.element,Cc(k));g.K(n,U);U.E4(k.B.element);n.SE();return n},H0m=function(k,U,n,Z,C){if(!k.player.U().Nf){var r=[];
U.navigationEndpoint&&g.e(U.navigationEndpoint,g.En)&&g.e(U.navigationEndpoint,g.En).browseId&&r.push(new aQi("openUrl","click",new Qgx(`/channel/${g.e(U.navigationEndpoint,g.En).browseId}`,"new",!0,!0)));var L=U.watermark.thumbnails[0];Z={channel_name:U.channelName,end_ms:U.endTimeMs,image_height:L.height,image_type:1,image_url:L.url,image_width:L.width,is_mobile:!1,session_data:{annotation_id:n,ei:C,feature:"iv",itct:U.trackingParams,src_vid:Z},start_ms:U.startTimeMs};if(U.subscribeButton&&g.e(U.subscribeButton,
g.a3)){Z.channel_id=g.e(U.subscribeButton,g.a3).channelId;U=g.e(U.subscribeButton,g.a3);L=C=null;U.subscribed?(U.subscriberCountWithUnsubscribeText&&(C=g.E8(U.subscriberCountWithUnsubscribeText)),U.subscriberCountText&&(L=g.E8(U.subscriberCountText))):(U.subscriberCountText&&(C=g.E8(U.subscriberCountText)),U.subscriberCountWithSubscribeText&&(L=g.E8(U.subscriberCountWithSubscribeText)));const F=g.e(U.signInEndpoint?.commandMetadata,g.bZ)?.url||"";U={subscribeText:g.E8(U.unsubscribedButtonText),subscribeCount:C||
"",unsubscribeText:g.E8(U.subscribedButtonText),unsubscribeCount:L||"",enabled:U.enabled||!1,classic:!1,subscribed:U.subscribed||!1,feature:"iv",signInUrl:F};Z.standalone_subscribe_button_data=U}r=new Z0E(n,"branding","branding",r,Z);Z=kVO(k);k.player.C("web_player_overlay_positioned_layout")?(Z.setAttribute("data-overlay-order","11"),k.player.cJ(Z,4,!0)):k.B.element.appendChild(Z);r=new C_Y(Z,Cc(k),r);r.SE();g.K(r,r);k.V[n]=r}};
g.wX.prototype.JG=g.nz(36,function(k,U){const n=g.D3(this.Il());n&&n.JG(k,U)});
var R7={},hP=null;g.JS(z1,g.gp);g.z=z1.prototype;g.z.getDuration=function(){return this.duration};
g.z.play=function(k){if(k||this.S==0)this.progress=0,this.coords=this.B;else if(this.isPlaying())return!1;bp(this);this.startTime=k=g.tS();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.J=this.startTime;this.progress||this.nV();this.Hh("play");this.isPaused()&&this.Hh("resume");this.S=1;const U=g.$k(this);U in R7||(R7[U]=this);r52();L5i(this,k);return!0};
g.z.stop=function(k){bp(this);this.S=0;k&&(this.progress=1);F5m(this,this.progress);this.onStop();this.wb()};
g.z.pause=function(){this.isPlaying()&&(bp(this),this.S=-1,this.Hh("pause"))};
g.z.Q$=function(){this.S==0||this.stop(!1);this.Hh("destroy");z1.nD.Q$.call(this)};
g.z.destroy=function(){this.dispose()};
g.z.e$=function(){this.Hh("animate")};
g.z.Hh=function(k){this.dispatchEvent(new vri(k,this))};
g.JS(vri,g.g5);g.JS(Q1,z1);Q1.prototype.j=function(){};
Q1.prototype.e$=function(){this.j();Q1.nD.e$.call(this)};
Q1.prototype.wb=function(){this.j();Q1.nD.wb.call(this)};
Q1.prototype.nV=function(){this.j();Q1.nD.nV.call(this)};
g.JS(KA,Q1);KA.prototype.j=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};var ELO=class extends g.ca{constructor(k){super();this.B=k||window;this.S=[]}listen(k,U,n,Z){n=(0,g.pz)(n,Z||this.B);k=g.ka(k,U,n);this.S.push(k);return k}AP(k,U,n,Z){n=(0,g.pz)(n,Z||this.B);k=ZK7(k,U,n);this.S.push(k);return k}V4(k){g.io(k);g.FO(this.S,k)}removeAll(){g.io(this.S);this.S.length=0}Q$(){this.removeAll();super.Q$()}};var Q1E=class extends g.eX{constructor(k){super(k);this.J=this.endscreen=null;this.B={};this.V={};this.W=this.j=null;this.X=[];this.S=null;this.dM=!0;this.L=0;k=k.U();this.D=g.Oj(k)||g.gr(k);this.events=new g.HW(this);g.K(this,this.events);this.events.K(this.player,g.aQ("creatorendscreen"),this.onCueRangeEnter);this.events.K(this.player,g.$g("creatorendscreen"),this.onCueRangeExit);this.events.K(this.player,"resize",this.DP);this.events.K(window,"focus",this.Y);this.load();const U=g.Ox("STYLE");(g.cr("HEAD")[0]||
document.body).appendChild(U);this.addOnDisposeCallback(()=>{g.Ex(U)});
U.sheet&&(U.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),U.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))}load(){super.load();if(!pA(this)){var k=g.XON(this.player.getVideoData());k?(k=$t(k,grV(this)),Nn(this,k,!1)):ds_(this)}}unload(){Nn(this,null);this.J&&(this.J.abort(),this.J=null);super.unload()}NT(k,U){return pA(this)?k==="loadCustomEndscreenRenderer"?(k=$t(U,"new"),Nn(this,k),!0):null:null}getOptions(){return pA(this)?["loadCustomEndscreenRenderer"]:[]}DP(){if(this.endscreen&&this.endscreen.elements){var k=this.player.getVideoContentRect();if(k&&k.width!==0&&k.height!==0){var U=this.player.getPlayerSize();
if(U&&U.width!==0&&U.height!==0){var n=k.width/k.height;var Z=0;var C=-1;for(var r=0;r<Rrm.length;r++){var L=Math.abs(U.width-Rrm[r]);if(C===-1||Z>=L)C=r,Z=L}Z=hrB[C];this.j&&g.Pl(this.j.element,"outline-width",Math.max(U.width,U.height)+"px");for(U=0;U<this.endscreen.elements.length;++U){r=this.endscreen.elements[U].id;C=this.B[r];L=this.V[r];if(!C||!L)continue;const v=L.width*n/L.aspectRatio;var F=Math.round(L.width*k.width);r=Math.round(v*k.height);const O=k.left+Math.round(L.left*k.width),w=k.top+
Math.round(L.top*k.height);g.m5(C.element,F,r);g.S6(C.element,O,w);g.wp(C.element,b02);F>256||r>256?g.F_(C.element,"ytp-ce-large-round"):F>96||r>96?g.F_(C.element,"ytp-ce-medium-round"):g.F_(C.element,"ytp-ce-small-round");g.wp(C.element,zrO);F=L.left+L.width/2;L=L.top+v/2;g.F_(C.element,F<=.5&&L<=.5?"ytp-ce-top-left-quad":F>.5&&L<=.5?"ytp-ce-top-right-quad":F<=.5&&L>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.wp(C.element,hrB);g.F_(C.element,Z);(C=g.mf(document,"div","ytp-ce-expanding-overlay-body",
C.element)[0])&&g.Pl(C,"height",`${r}px`)}}}}}onCueRangeEnter(k){if(this.endscreen)if(k.getId()==="ytp-ce-in-endscreen")BF(this,this.endscreen.impressionUrls),(k=g.Tz())&&this.endscreen.visualElement&&g.ZN(k,this.endscreen.visualElement),this.S&&(g.F_(this.S,"ytp-ce-element-show"),this.S.removeAttribute("aria-hidden"),this.player.ow()?g.F_(this.S,"ytp-ce-hide-button-lower"):g.Oe(this.S,"ytp-ce-hide-button-lower"));else{k=k.getId().substring(15);var U=this.B[k],n=this.V[k];g.F_(U.element,"ytp-ce-element-show");
U.element.removeAttribute("aria-hidden");U=this.player.getRootNode();g.F_(U,"ytp-ce-shown");BF(this,n.impressionUrls);(U=g.Tz())&&g.ZN(U,n.visualElement);this.player.U().X&&g.LB(this.player,"endscreenelementshown",k)}}onCueRangeExit(k){if(k.getId()==="ytp-ce-in-endscreen")this.S&&(g.Oe(this.S,"ytp-ce-element-show"),this.S.setAttribute("aria-hidden","true"));else{k=k.getId().substring(15);var U=this.B[k];g.Oe(U.element,"ytp-ce-element-show");U.element.setAttribute("aria-hidden","true");U=this.player.getRootNode();
g.Oe(U,"ytp-ce-shown");this.player.U().X&&g.LB(this.player,"endscreenelementhidden",k)}}Y(k){k.target===window&&(new g.iX(()=>{for(const U of Object.values(this.B))g.wp(U.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()}Uj(k){for(const U of Object.values(this.B))k?U.element.setAttribute("hidden",""):U.element.removeAttribute("hidden")}lH(k){this.S&&this.player.getRootNode().removeChild(this.S);
k&&(g.F_(k,"ytp-ce-hide-button-container"),this.S=k,g.$Z(this.player,this.S,4))}},Rrm=[346,426,470,506,570,640,853,1280,1920],hrB="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),zrO=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],b02=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var Qgx=class{constructor(k,U,n,Z){this.value=k;this.target=U;this.showLinkIcon=n;this.B=Z}S(){return this.value?this.value:null}},zJp={dA:"current",c5:"new"};var aQi=class{constructor(k,U,n){this.type=k;this.trigger=U;this.url=n}},K5V={CLOSE:"close",OE:"openUrl",SUBSCRIBE:"subscribe"},T8O={K_:"click",CLOSE:"close",Eg:"hidden",XyE:"rollOut",HNy:"rollOver",GJ0:"shown"};var Z0E=class{constructor(k,U,n,Z,C){this.id=k;this.type=U;this.style=n;this.data=C;this.action=Z||[]}Hn(){const k=plx(this,U=>U.type==="openUrl"&&U.url!=null);
return k?k.url:null}},nLm={sT:"anchored",vr:"branding",CHANNEL:"channel",PZ:"cta",pk:"highlightText",WG:"label",PLAYLIST:"playlist",POPUP:"popup",kQ4:"speech",SUBSCRIBE:"subscribe",JSM:"title",VIDEO:"video",vo$:"website"},UP7={vr:"branding",Ox:"card",WZ:"drawer",VM:"highlight",nI:"marker",Gc:"promotion",TEXT:"text",tpJ:"widget"};var KdB=[".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}"],
Ttm=[".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}"];var aC_=class{constructor(k,U){this.context=k;this.S=U}};var Fd7=class{constructor(k,U){this.merchant=k;this.price=U}};var $Pb=class extends g.ca{constructor(k,U){super();this.element=k;this.context=U;this.Fo=!1;this.Xo=new Map;this.uL=new Map;this.context.O.addEventListener(g.aQ("annotations_module"),n=>{(n=this.Xo.get(n))&&n.apply(this)});
this.context.O.addEventListener(g.$g("annotations_module"),n=>{(n=this.uL.get(n))&&n.apply(this)})}addCueRange(k,U,n,Z,C){k=new g.sc(k,U,{id:n,
namespace:"annotations_module"});Z&&this.Xo.set(k,Z);C&&this.uL.set(k,C);this.context.O.oA([k],1)}SE(){this.context.B.subscribe("resize",this.Wy,this)}j5(){return this.element}aQ(k,U,n,Z,C,r){if(this.Fo)return!1;r&&(r.stopPropagation(),r.preventDefault());this.navigate(k,n,Z,C);return!1}show(){}hide(){}destroy(){g.Ex(this.j5())}Wy(){}navigate(k,U,n,Z){const C=k.S();if(C){var r=IQY(C,k.target),L=()=>{k.B&&this.context.O.pauseVideo();const F=this.context.videoData.wm||!1,v=g.Qt(C||"");F&&v&&(v.v||v.list)?
this.context.O.OQ(v.v,U,v.list,!1):g.Ck(C||"",r==="current"?"_top":void 0,U)};
r==="new"&&(L(),L=null);Zz(this.context.logger,n,L,Z);t6V(C)||(n=g.Tz(),Z=U.itct,n&&Z&&g.L_(n,g.bf(Z)))}}Q$(){this.Xo.clear();this.uL.clear();super.Q$()}createElement(k){k=new g.l(k);g.K(this,k);return k.element}};var V_B=class extends $Pb{constructor(k,U,n){super(U,n);this.O=k;this.eventId=null;this.xo=this.V$=this.tS=this.j=this.isInitialized=!1;this.cards=[];this.h8=this.W=this.IQ=this.V=this.TJ=this.S=null;this.dM=[];this.Y=this.X=this.sJ=this.eE=null;this.L=0;this.By=new g.iX(()=>{},n.k$.DD?4E3:3E3);
g.K(this,this.By);this.GJ=new g.iX(()=>{});
g.K(this,this.GJ);this.x$=new aC_(n,(Z,C,r,L,F,v)=>{G1(this,Z,C,r,L,F,v)});
this.D=new g.l({Z:"div",A:"iv-drawer",N:{id:"iv-drawer"},G:[{Z:"div",A:"iv-drawer-header",N:{"aria-role":"heading"},G:[{Z:"span",A:"iv-drawer-header-text"},{Z:"button",O4:["iv-drawer-close-button","ytp-button"],N:{"aria-label":"Hide cards",tabindex:"0"}}]},{Z:"div",A:"iv-drawer-content"}]});g.K(this,this.D);this.J=this.D.element;this.bL=new g.Wf(this.D,330);g.K(this,this.bL);this.Y$=g.xC("iv-drawer-header-text",this.J);this.B=g.xC("iv-drawer-content",this.J);this.addCueRange(0,n.videoData.lengthSeconds*
1E3,"",()=>{this.tS&&cF(this,"YOUTUBE_DRAWER_AUTO_OPEN")},()=>{(this.tS=this.j)&&m2(this)});
this.pN=new g.HW(this);g.K(this,this.pN);this.O.addEventListener("videodatachange",this.kf.bind(this))}kf(){this.Y&&lp(this,this.Y)}isAvailable(){var k;if(k=!!this.cards.length)(k=this.O.getRootNode())?(k=g.xr(k),k=173<k.width&&173<k.height):k=!1;return k}Wy(){const k=this.isAvailable();g.kL(this.j5(),k);g.N(this.context.O.getRootNode(),g.ge.IV_DRAWER_ENABLED,k);V1(this.O)}destroy(){this.O.JG(!1);try{this.O.getRootNode().removeChild(this.J)}catch(k){}g.LN(this.dM);this.pN.B();this.TJ&&this.TJ.dispose();
this.V&&this.V.dispose();super.destroy()}n$(){this.context.S.listen(g.xC("iv-drawer-close-button",this.J),"click",this.gt,this);this.context.S.listen(this.B,"touchend",()=>{this.By.start()});
this.context.S.listen(this.B,"scroll",this.Hc,this);this.context.B.subscribe("onHideControls",()=>{this.V$=!0});
this.context.B.subscribe("onShowControls",()=>{this.V$=!1});
this.context.B.subscribe("onVideoAreaChange",()=>{this.V$=g.L2(this.O.getRootNode(),"ytp-autohide")});
this.dM.push(g.rk("iv-button-shown",this.Nf,this));this.dM.push(g.rk("iv-button-hidden",this.lZ,this));PAs(this)}findLastIndex(k){if(this.cards.length===0)return 0;const U=g.i2(this.cards,n=>k.OJ.startMs>n.OJ.startMs||k.OJ.startMs===n.OJ.startMs&&k.OJ.timestamp>=n.OJ.timestamp?!0:!1);
return U===-1?0:U+1}gt(){if(this.j){Zz(this.context.logger,i8(this).Pu.close);var k=g.Tz();k&&this.X&&g.L_(k,this.X);m2(this)}}Hc(){g.N(this.J,"iv-drawer-scrolled",this.B.scrollTop>0)}Nf(){const k=g.Tz();var U=i8(this);U=U?U.sJ:this.sJ;k&&U&&g.C_(k,[U])}lZ(){const k=g.Tz();var U=i8(this);U=U?U.sJ:this.sJ;k&&U&&g.ry(k,[U])}V3(){const k=i8(this);Zz(this.context.logger,k.Pu.Du);const U=g.Tz();if(U&&k)if(this.O.C("web_infocards_teaser_show_logging_fix")){const n=[];k.K2&&n.push(k.K2);k.sJ&&n.push(k.sJ);
n.length>0&&g.C_(U,n)}else g.C_(U,[k.K2,k.sJ])}PV(){const k=g.Tz(),U=i8(this);k&&U&&g.ry(k,[U.K2])}e5(k){const U=i8(this),n=g.Tz();this.S?k?(k=this.context.logger,Zz(k,U.Pu.CM),k.O.sendVideoStatsEngageEvent(4,void 0),n&&U.K2&&g.L_(n,U.K2)):(k=this.context.logger,Zz(k,U.Pu.CM),k.O.sendVideoStatsEngageEvent(4,void 0),n&&U.sJ&&g.L_(n,U.sJ)):(k=this.context.logger,Zz(k,U.Pu.CM),k.O.sendVideoStatsEngageEvent(4,void 0),n&&this.sJ&&g.L_(n,this.sJ))}};var p_b=class extends $Pb{constructor(k,U,n){super(k,U);this.annotation=n;this.isActive=!1}SE(){super.SE();GK8(this)}show(){super.show();const k=g.Tz();var U=this.annotation.data;k&&U&&(U=U.session_data)&&g.C_(k,[g.bf(U.itct)])}hide(){super.hide();const k=g.Tz();var U=this.annotation.data;k&&U&&(U=U.session_data)&&g.ry(k,[g.bf(U.itct)])}};var C_Y=class extends p_b{constructor(k,U,n){super(k,U,n);this.S=null;this.j=!1;this.B=null}show(){if(!this.isActive){super.show();if(!this.j){g.F_(this.j5(),"iv-branding");const k=this.annotation.data;this.S=this.createElement({Z:"img",O4:["branding-img","iv-click-target"],N:{"aria-label":"Channel watermark",src:k.image_url,width:k.image_width,height:k.image_height}});g.kL(this.S,!1);const U=this.createElement({Z:"button",O4:["branding-img-container","ytp-button"]});U.appendChild(this.S);this.j5().appendChild(U);
const n=this.annotation.Hn();n&&G1(this,U,n,this.annotation.id,k.session_data);this.j=!0}g.kL(this.j5(),!0);this.isActive=!0;if(this.S){try{fQO(this,this.S)}catch{}g.F_(this.context.O.getRootNode(),"ytp-branding-shown");this.context.O.getRootNode().style.setProperty("--branding-image-width",`${this.S.getAttribute("width")}px`)}}}hide(){this.isActive&&(super.hide(),g.kL(this.j5(),!1),this.isActive=!1,g.Oe(this.context.O.getRootNode(),"ytp-branding-shown"))}destroy(){this.B&&(this.B.dispose(),this.B=
null);g.Oe(this.context.O.getRootNode(),"ytp-branding-shown");super.destroy()}};var AKb=class{constructor(k,U,n,Z,C,r,L){this.S=k;this.j=U;this.k$=n;this.videoData=Z;this.logger=C;this.O=r;this.B=L}};var rKb=class extends p_b{constructor(k,U,n){super(k,U,n);this.X=this.isCollapsed=this.D=!1;this.V=5E3;this.B=this.j=this.S=this.J=null;this.L=this.createElement({Z:"div",O4:["iv-promo-contents"]});this.W=new g.iX(()=>{this.S.setAttribute("aria-hidden","true");g.kL(this.j,!1);g.kL(this.B,!0)},700,this);
g.K(this,this.W)}show(){this.isActive||(super.show(),this.D||(c57(this),this.D=!0),g.kL(this.j5(),!0),g.Oh(function(){g.Oe(this.j5(),"iv-promo-inactive")},100,this),this.j5().removeAttribute("aria-hidden"),this.isActive=!0,nc(this),M6V(this),y58(this,this.V))}hide(){this.isActive&&(g.F_(this.j5(),"iv-promo-inactive"),this.isActive=!1,this.j5().setAttribute("aria-hidden","true"))}aQ(k,U,n,Z,C,r){return this.isCollapsed?!1:super.aQ(k,U,n,Z,C,r)}By(k){this.X=!0;
U3(this,500,k)}x$(){this.X=!1;lQO(this)}dM(k){k.stopPropagation();this.hide()}Y(k){k.stopPropagation();nc(this);this.isCollapsed=!0;g.F_(this.j5(),"iv-promo-collapsed-no-delay");this.W.start()}destroy(){this.W.dispose();super.destroy()}};var Nts=class{constructor(k){this.O=k}};g.Jq("annotations_module",class extends g.eX{constructor(k){super(k);this.dM=this.Y=!1;this.loadNumber=0;this.V={};this.logger=new Nts(this.player);this.W=new g.HW(this);this.L=this.J=null;this.events=new g.HW(this);this.L1=this.X=this.S=null;this.SE=[];g.K(this,this.W);this.W.K(this.player,"onVideoAreaChange",()=>{this.publish("onVideoAreaChange")});
this.W.K(this.player,"onHideControls",()=>{this.publish("onHideControls")});
this.W.K(this.player,"onShowControls",()=>{this.publish("onShowControls")});
this.W.K(this.player,"resize",n=>{this.publish("resize",n)});
this.W.K(this.player,"presentingplayerstatechange",n=>{this.publish("presentingplayerstatechange",n)});
this.subscribe("presentingplayerstatechange",this.By,this);this.subscribe("resize",this.D,this);this.player.U().eE.subscribe("vast_info_card_add",this.x$,this);g.K(this,this.events);this.Wy=this.createElement({Z:"div",A:"video-custom-annotations"});this.B=new g.l({Z:"div",O4:["ytp-player-content","ytp-iv-player-content"]});g.K(this,this.B);g.$Z(this.player,this.B.element,4);this.B.hide();this.j=new g.l({Z:"div",O4:["ytp-iv-video-content"]});g.K(this,this.j);k=this.createElement({Z:"div",A:"video-annotations"});
k.appendChild(this.Wy);this.j.element.appendChild(k);this.L4()?this.load():this.player.C("web_fix_annotations")&&(this.J=()=>{this.loaded||this.LN()||!this.L4()||(xsO(this),this.load())},this.player.addEventListener("videodatachange",this.J));
const U=this.createElement({Z:"style"});(g.cr("HEAD")[0]||document.body).appendChild(U);this.addOnDisposeCallback(()=>{g.Ex(U)});
if(k=U.sheet){for(const n of KdB)k.insertRule(n,0);for(const n of Ttm)k.insertRule(n,0)}}NT(k,U){if(!ms7(this.player.U().playerStyle))return null;switch(k){case "loadCustomAnnotationsXml":return(k=g.Ve(U))&&rO(this,k),!0;case "removeCustomAnnotationById":return U&&this.S&&(Mn(this.S,U),V1(this.player)),!0}return null}getOptions(){return ms7(this.player.U().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]}L4(){const k=this.player.getVideoData(),U=k.getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer;
return k.wm||this.player.isMutedByEmbedsMutedAutoplay()?!1:this.player.C("web_fix_annotations")?vLi(this)?U?.isWatermarkEnforced===!0?!0:U?.isAnnotationsEnabled??!1:!1:vLi(this)}D(){if(this.j){var k=this.player.vy().getVideoContentRect(!0);g.m5(this.j.element,k.width,k.height);g.S6(this.j.element,k.left,k.top)}if(this.S){var U=this.player.YG();k=this.S;U=U.width;g.N(k.J,"iv-drawer-small",U<=426);g.N(k.J,"iv-drawer-big",U>=1280)}}By(k){O0m(this,k.state);k.state.S(2)&&(this.ow()&&this.n5()&&this.player.getPresentingPlayerType()!==
2&&this.We(!1),this.JG(!1))}load(){super.load();O0m(this,this.player.getPlayerStateObject());this.loadNumber++;const k=this.player.getVideoData();X_i(this,k);g.$Z(this.player,this.j.element,4);this.D();var U=g.lT(k);const n=k.oi();if(this.player.C("web_fix_annotations")){if(U&&(U.featuredChannel&&H0m(this,U.featuredChannel,U.annotationId||"branding",k.videoId||null,k.eventId||null),U=this.player.getVideoData().getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer,U?.isWatermarkEnforced&&!U?.isAnnotationsEnabled))return;
n&&Lc(this,n)}else n&&Lc(this,n),U&&U.featuredChannel&&H0m(this,U.featuredChannel,U.annotationId||"branding",k.videoId||null,k.eventId||null);this.L1=g.xC("ytp-cards-button",this.player.getRootNode());k.ef()&&gL7(this,k)}onVideoDataChange(){}unload(){this.player.Wn("annotations_module");for(const k of Object.keys(this.V))this.V[k].destroy();this.X=null;this.S&&(this.S.destroy(),this.S=null,V1(this.player));this.Y=!1;this.L&&(this.L.abort(),this.L=null);this.dM=!1;this.V={};this.B.hide();super.unload();
this.j.detach();xsO(this)}x$(k){k===this.player.getVideoData().videoId&&(this.loaded?dP2(this):this.load())}ow(){return this.S?.isAvailable()||this.dM}n5(){return!!this.S&&this.S.j}We(k,U=!1,n){this.ow();this.S&&(k?n?cF(this.S,n,U):cF(this.S,"YOUTUBE_DRAWER_AUTO_OPEN",U):m2(this.S))}JG(k,U){this.player.publish(k?"cardsteasershow":"cardsteaserhide",U)}Q$(){this.player.U().eE.unsubscribe("vast_info_card_add",this.x$,this);g.Oe(this.player.getRootNode(),g.ge.IV_DRAWER_OPEN);var k=this.SE,U=g.Sn;for(let n=
0,Z=k.length;n<Z;n++)U.vu(k[n]);this.SE.length=0;super.Q$()}createElement(k){k=new g.l(k);g.K(this,k);return k.element}});g.Jq("creatorendscreen",Q1E);})(_yt_player);
